# Generated by Django 4.1.3 on 2022-11-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.grade",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="interests",
            field=models.ManyToManyField(blank=True, to="authentication.schoolsubject"),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.school",
            ),
        ),
    ]
