# Generated by Django 4.1.3 on 2022-11-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="teacher",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="grade",
            name="id",
        ),
        migrations.RemoveField(
            model_name="school",
            name="id",
        ),
        migrations.RemoveField(
            model_name="schoolsubject",
            name="id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user_ptr",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="user_ptr",
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="student status"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="teacher status"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="schoolsubject",
            name="name",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
