# Generated by Django 4.1.3 on 2022-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="long_description",
            field=models.TextField(
                default="Voii une longue description a propos de moi", max_length=1000
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="short_description",
            field=models.TextField(
                default="Voici une courte description a propos de moi", max_length=200
            ),
            preserve_default=False,
        ),
    ]
