# Generated by Django 4.1.3 on 2022-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_student_options_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="interests",
            field=models.ManyToManyField(to="authentication.schoolsubject"),
        ),
    ]
