# Generated by Django 4.1.3 on 2022-11-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_teacher_long_description_teacher_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="profile_picture",
            field=models.ImageField(
                default="static/images/avatar.jpg", upload_to="static/images/"
            ),
        ),
    ]
